#!/usr/bin/env bash

# ncctl - build and/or install coreutils.
# Warn: this may not work.

src='./src/'
bin='./bin/'
prefix='/usr'

install() {
    install -m 0755 bin/mkdir $prefix/bin/NCmkdir    
    install -m 0755 bin/touch $prefix/bin/NCtouch    
    install -m 0755 bin/ln $prefix/bin/NCln    
    install -m 0755 bin/ls $prefix/bin/NCls    
    install -m 0755 bin/rm $prefix/bin/NCrm
    install -m 0755 bin/date $prefix/bin/NCdate
    install -m 0755 bin/uname $prefix/bin/NCuname
    echo "Installed."    
    echo "Note that all Neuecoreutils apps have the 'NC' prefix."

    if [ $? == 1 ]; then
        echo "$0: Installation failed"
        exit 1
    elif [ $? == 0 ]; then
        echo "$0: Installation successful."
        exit 0
    else
        echo "$0: Unknown error?"
        exit 1
    fi    
}

build() {
    mkdir bin/
    swiftc src/ln.swift -o bin/ln
    swiftc src/ls.swift -o bin/ls
    swiftc src/mkdir.swift -o bin/mkdir
    swiftc src/rm.swift -o bin/rm
    swiftc src/touch.swift -o bin/touch
    swiftc src/date.swift -o bin/date
    swiftc src/c/uname.swift -o bin/uname

    if [ $? == 1 ]; then
        echo "$0: Compilation failed"
        exit 1
    elif [ $? == 0 ]; then
        echo "$0: Compilation successful."
        exit 0
    else
        echo "$0: Unknown error?"
        exit 1
    fi
}

uninstall() {
    rm -f $prefix/bin/NCmkdir    
    rm -f $prefix/bin/NCtouch    
    rm -f $prefix/bin/NCln    
    rm -f $prefix/bin/NCls    
    rm -f $prefix/bin/NCrm

    if [ $? == 1 ]; then
        echo "$0: Installation failed"
        exit 1
    elif [ $? == 0 ]; then
        echo "$0: Neuecoreutils have been uninstalled."
        exit 0
    else
        echo "$0: Unknown error?"
        exit 1
    fi    
}


case "$1" in
    "--install")
        install
    "--build")
        build
    "--uninstall")
        uninstall
    *)
        echo "$0: Error: No command given."
        exit 127
esac