#!/usr/bin/env bash

# ncctl - build and/or install coreutils.
# Warn: this may not work.

# Point ncctl to the appropriate directories according to your need.

src='./src/'
bin='./bin/'
prefix='/usr'

# Change the compiler according to your need

swift_c='swiftc'
cc='gcc'

install() {
    install -m 0755 bin/NCmkdir $prefix/bin/NCmkdir    
    install -m 0755 bin/NCtouch $prefix/bin/NCtouch    
    install -m 0755 bin/NCln $prefix/bin/NCln    
    install -m 0755 bin/NCls $prefix/bin/NCls    
    install -m 0755 bin/NCrm $prefix/bin/NCrm
    install -m 0755 bin/NCdate $prefix/bin/NCdate
    install -m 0755 bin/NCuname $prefix/bin/NCuname
    install -m 0755 bin/NCuname $prefix/bin/NCcp
    install -m 0755 bin/NCuname $prefix/bin/NCmv
    install -m 0755 bin/NCuname $prefix/bin/NCwhoami
    echo "Installed."    
    echo "Note that all Neuecoreutils apps have the 'NC' prefix."

    if [ $? == 1 ]; then
        echo "$0: Installation failed"
        exit 1
    elif [ $? == 0 ]; then
        echo "$0: Installation successful."
        exit 0
    else
        echo "$0: Unknown error? Kind of ignore as this prints it everytime it succeeds."
    fi    
}

build() {
    mkdir bin/
    $swift_c src/ln.swift -o bin/NCln
    $swift_c src/ls.swift -o bin/NCls
    $swift_c src/mkdir.swift -o bin/NCmkdir
    $swift_c src/rm.swift -o bin/NCrm
    $swift_c src/touch.swift -o bin/NCtouch
    $swift_c src/date.swift -o bin/NCdate
    $swift_c src/mv.swift -o bin/NCmv
    $swift_c src/cp.swift -o bin/NCcp
    $swift_c src/whoami.swift -o bin/NCwhoami
    $cc src/c/uname.c -o bin/NCuname

    if [ $? == 1 ]; then
        echo "$0: Compilation failed"
        exit 1
    elif [ $? == 0 ]; then
        echo "$0: Compilation successful."
        exit 0
    else
        echo "$0: Unknown error?"
        exit 1
    fi
}

uninstall() {
    rm -f $prefix/bin/NCmkdir    
    rm -f $prefix/bin/NCtouch    
    rm -f $prefix/bin/NCln    
    rm -f $prefix/bin/NCls    
    rm -f $prefix/bin/NCrm
    rm -f $prefix/bin/NCuname
    rm -f $prefix/bin/NCdate
    rm -f $prefix/bin/NCcp
    rm -f $prefix/bin/NCmv
    rm -f $prefix/bin/NCwhoami

    if [ $? == 1 ]; then
        echo "$0: Installation failed"
        exit 1
    elif [ $? == 0 ]; then
        echo "$0: Neuecoreutils have been uninstalled."
        exit 0
    else
        echo "$0: Unknown error?"
        exit 1
    fi    
}


case "$1" in
    "--install")
        install
    ;;
    "--build")
        build
    ;;
    "--uninstall")
        uninstall
    ;;
    *)
        echo "$0: Error: No command given."
        exit 127
esac